### ISSUE TITLE
YMM3からの自動起動時に "Fonts directory is missing"

### ISSUE THREAD

**Issue by khsk** [khsk/AviUtl-LocalFontPlugin#1]
https://qiita.com/khsk/items/997adf671dfae94bb455#comment-2d1955f1c406926bd7e8

**Comment by khsk** [comment]
再現できないのでテスト修正版
人柱待ち
[test.zip](https://github.com/khsk/AviUtl-LocalFontPlugin/files/5112315/test.zip)
詳細はQiitaのほうに書いておくことにします

**Comment by mitosagi** [comment]
AviUtlをショートカットから起動した場合にも`Fonts directory is missing`が表示されますが、テスト修正版では修正されているようです。

これをリリースしていただくことは可能ですか？

**Comment by khsk** [comment]
報告ありがとうございます！
テスト修正版とほぼ同じ修正版をリリースしました。
動作が多少異なりますが発生している問題にはおそらく影響は無いと思います。

---
同様の問題報告
https://twitter.com/bakegaki/status/1356620631400304642
